[CmdletBinding()]
param(
    [string]$OutputPath = "SKILL.md",
    [string]$SourceVersion = "repository source",
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$outputFullPath = if ([System.IO.Path]::IsPathFullyQualified($OutputPath)) {
    $OutputPath
}
else {
    [System.IO.Path]::GetFullPath((Join-Path $repositoryRoot $OutputPath))
}
$indexPath = Join-Path $repositoryRoot "docs/index.md"

$packageDocuments = [regex]::Matches(
    [System.IO.File]::ReadAllText($indexPath),
    '\]\(packages/(?<file>[-a-z0-9]+\.md)\)'
) | ForEach-Object {
    "docs/packages/$($_.Groups["file"].Value)"
} | Select-Object -Unique

$sourcePaths = @(
    "docs/agent-guidance.md"
    "docs/index.md"
    "docs/getting-started.md"
) + $packageDocuments

function Convert-Document {
    param(
        [string]$Path,
        [string]$Content
    )

    if ($Path -eq "docs/agent-guidance.md") {
        $content = [regex]::Replace($Content, '(?m)^# Agent workflow$', '## Agent workflow')
    }
    else {
        $content = [regex]::Replace($Content, '(?m)^(#+) ', '$1# ')
    }

    if ($Path -eq "docs/index.md" -or $Path -eq "docs/getting-started.md") {
        $content = $content.Replace("](getting-started.md)", "](docs/getting-started.md)")
        $content = $content.Replace("](contributing.md)", "](docs/contributing.md)")
        $content = $content.Replace("](index.md)", "](docs/index.md)")
        $content = $content.Replace("](packages/", "](docs/packages/")
    }
    elseif ($Path.StartsWith("docs/packages/")) {
        $content = $content.Replace("](../getting-started.md)", "](docs/getting-started.md)")
        $content = $content.Replace("](../index.md)", "](docs/index.md)")
        $content = [regex]::Replace(
            $content,
            '\]\((?<file>[-a-z0-9]+\.md)\)',
            '](docs/packages/${file})'
        )
    }

    return $content.Trim()
}

function Test-Skill {
    param([string]$Content)

    $requiredHeadings = @(
        "## Agent workflow"
        "## Environment variables and secrets"
        "## Infrastructure and deployment"
        "## Troubleshooting and testing"
        "## Compatibility and deeper documentation"
        "## MDev.Dotnet documentation"
        "## Getting started"
    )

    foreach ($heading in $requiredHeadings) {
        if ($Content -notmatch "(?m)^$([regex]::Escape($heading))$") {
            throw "Generated skill is missing required heading '$heading'."
        }
    }

    $projects = Get-ChildItem (Join-Path $repositoryRoot "src") -Filter "MDev.Dotnet.*.csproj" -Recurse
    foreach ($project in $projects) {
        if (-not $Content.Contains("## $($project.BaseName)")) {
            throw "Generated skill does not document package '$($project.BaseName)'."
        }
    }

    if (([regex]::Matches($Content, '(?m)^```').Count % 2) -ne 0) {
        throw "Generated skill contains an unclosed code fence."
    }

    if ($Content -match '\{\{|\}\}|(?im)\b(TODO|TBD)\b') {
        throw "Generated skill contains an unresolved placeholder."
    }

    $secretPatterns = @(
        '-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----'
        '\bgh[pousr]_[A-Za-z0-9_]{20,}\b'
        '(?i)\b(AccountKey|SharedAccessSignature)=[^;\s]+'
    )
    foreach ($pattern in $secretPatterns) {
        if ($Content -match $pattern) {
            throw "Generated skill contains content resembling a credential."
        }
    }

    foreach ($link in [regex]::Matches($Content, '\[[^\]]+\]\((?<target>[^)]+)\)')) {
        $target = $link.Groups["target"].Value.Split('#')[0]
        if (-not $target -or $target -match '^[a-z][a-z0-9+.-]*:' -or $target.StartsWith("#")) {
            continue
        }

        $linkedPath = Join-Path $repositoryRoot $target
        if (-not (Test-Path $linkedPath)) {
            throw "Generated skill contains a broken repository link: $target"
        }
    }
}

$sourceContent = foreach ($path in $sourcePaths) {
    $fullPath = Join-Path $repositoryRoot $path
    if (-not (Test-Path $fullPath -PathType Leaf)) {
        throw "Skill source does not exist: $path"
    }
    [System.IO.File]::ReadAllText($fullPath).Replace("`r`n", "`n")
}

$digestInput = [string]::Join("`n---`n", $sourceContent)
$digestBytes = [System.Security.Cryptography.SHA256]::HashData(
    [System.Text.Encoding]::UTF8.GetBytes($digestInput)
)
$sourceDigest = [Convert]::ToHexString($digestBytes).ToLowerInvariant()

$sections = for ($index = 0; $index -lt $sourcePaths.Count; $index++) {
    Convert-Document -Path $sourcePaths[$index] -Content $sourceContent[$index]
}

$generated = @"
---
name: mdev-dotnet
description: Configure and use MDev.Dotnet packages securely in .NET applications and Azure workloads.
---

# MDev.Dotnet agent skill

> Generated by ``scripts/Generate-Skill.ps1`` from the versioned documentation. Do not edit this file directly.

- Source version: $SourceVersion
- Source content SHA-256: ``$sourceDigest``
- Stable source: [MDev.Dotnet repository](https://github.com/mathieumack/MDev.Dotnet)

$([string]::Join("`n`n---`n`n", $sections))
"@.Replace("`r`n", "`n").TrimEnd() + "`n"

Test-Skill -Content $generated

if ($Check) {
    if (-not (Test-Path $outputFullPath -PathType Leaf)) {
        throw "$OutputPath is missing. Run scripts/Generate-Skill.ps1."
    }

    $existing = [System.IO.File]::ReadAllText($outputFullPath).Replace("`r`n", "`n")
    if ($existing -cne $generated) {
        throw "$OutputPath is stale. Run scripts/Generate-Skill.ps1 and commit the result."
    }

    Write-Host "$OutputPath is current and valid."
    exit 0
}

$outputDirectory = Split-Path -Parent $outputFullPath
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[System.IO.File]::WriteAllText(
    $outputFullPath,
    $generated,
    [System.Text.UTF8Encoding]::new($false)
)
Write-Host "Generated $OutputPath."
