name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        publishToNuget:
          description: 'Publish to nuget'
          required: true
          default: true
          type: boolean

jobs:
  dotnet-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mathieumack/MyGithubActions/actions/buildandtestdotnet@main
        with:
          workingDirectory: 'src'
          dotnet-version: |
            9.0.x
            10.0.x
          version: '0.0.0'
  dotnet:
    if: github.event_name != 'pull_request'
    uses: mathieumack/MyGithubActions/.github/workflows/dotnetlib.yml@main
    with:
      sourceDirectoryPath: 'src'
      publishToNuget: ${{ github.event.inputs.publishToNuget == true }}
      dotnet-version: |
        9.0.x
        10.0.x
    secrets:
      NUGETPACKAGEIDENTIFIER: ${{ secrets.NUGETPACKAGEIDENTIFIER }}
      NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
